# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class Api:
        type: str
        url: str
    class Frontend:
        type: str
        url: str
    class IdentityPool:
        id: str
        type: str
    class Media:
        name: str
        type: str
    class Uploads:
        name: str
        type: str
    class UserPool:
        id: str
        type: str
    class UserPoolClient:
        id: str
        secret: str
        type: str

